---
driver:
  name: vagrant
  network:
      - ["forwarded_port", {guest: 9010, host: 9010}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: debian-7.4

suites:
  - name: default
    run_list:
      - recipe[webzilla-gemserver::default]
      - recipe[webzilla-gemserver::gitdeploy]
    attributes:
