---
driver:
  name: vagrant
  http_proxy: http://192.168.1.3:8123
  https_proxy: http://192.168.1.3:8123
  provision_command: "env http_proxy=http://192.168.1.3:8123 bash -c 'curl -L http://www.getchef.com/chef/install.sh | bash'"
  network:
      - ["forwarded_port", {guest: 9010, host: 9010}]

provisioner:
  chef_omnibus_url: http://www.getchef.com/chef/install.sh

platforms:
  - name: ubuntu-12.04
  - name: debian-7.4

suites:
  - name: default
    data_bags_path: "data_bags"
    run_list:
      - recipe[webzilla-gemserver::default]
      - recipe[webzilla-gemserver::gitdeploy]
    attributes:
